scrape:
  url: "https://untappd.com/v/brouwcafe-de-molen/75672"
  draft_section: "on draft" # case-insensitive substring match on section heading
  page_timeout_seconds: 30

schedule:
  cron: "*/30 * * * *" # standard 5-field cron;
  # cron: "1 17 * * *" # standard 5-field cron;

brewers:
  - "puhaste"
  - "pohjala"

ntfy:
  topic: "zaohome"
  base_url: "https://ntfy.sh" # override for self-hosted ntfy instance
  priority: "default" # min | low | default | high | max
  tags:
    - "beer"
    - "tada"
